package com.example.habicted_app.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF6524A2)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF8C4EC9)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF6D5484)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8CDFF)
val onSecondaryContainerLight = Color(0xFF4E3765)
val tertiaryLight = Color(0xFF88165D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB63F83)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF7FE)
val onBackgroundLight = Color(0xFF1E1A22)
val surfaceLight = Color(0xFFFFF7FE)
val onSurfaceLight = Color(0xFF1E1A22)
val surfaceVariantLight = Color(0xFFEBDEF0)
val onSurfaceVariantLight = Color(0xFF4C4452)
val outlineLight = Color(0xFF7D7483)
val outlineVariantLight = Color(0xFFCEC2D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF332F37)
val inverseOnSurfaceLight = Color(0xFFF7EEF9)
val inversePrimaryLight = Color(0xFFDDB8FF)
//val surfaceDimLight = Color(0xFFE0D7E2)
//val surfaceBrightLight = Color(0xFFFFF7FE)
//val surfaceContainerLowestLight = Color(0xFFFFFFFF)
//val surfaceContainerLowLight = Color(0xFFFAF1FC)
//val surfaceContainerLight = Color(0xFFF4EBF6)
//val surfaceContainerHighLight = Color(0xFFEFE5F0)
//val surfaceContainerHighestLight = Color(0xFFE9DFEB)

val primaryLightMediumContrast = Color(0xFF5F1B9B)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF8C4EC9)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF503967)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF846A9C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF800D57)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFB63F83)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7FE)
val onBackgroundLightMediumContrast = Color(0xFF1E1A22)
val surfaceLightMediumContrast = Color(0xFFFFF7FE)
val onSurfaceLightMediumContrast = Color(0xFF1E1A22)
val surfaceVariantLightMediumContrast = Color(0xFFEBDEF0)
val onSurfaceVariantLightMediumContrast = Color(0xFF48404E)
val outlineLightMediumContrast = Color(0xFF655C6B)
val outlineVariantLightMediumContrast = Color(0xFF817787)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF332F37)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF7EEF9)
val inversePrimaryLightMediumContrast = Color(0xFFDDB8FF)
//val surfaceDimLightMediumContrast = Color(0xFFE0D7E2)
//val surfaceBrightLightMediumContrast = Color(0xFFFFF7FE)
//val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightMediumContrast = Color(0xFFFAF1FC)
//val surfaceContainerLightMediumContrast = Color(0xFFF4EBF6)
//val surfaceContainerHighLightMediumContrast = Color(0xFFEFE5F0)
//val surfaceContainerHighestLightMediumContrast = Color(0xFFE9DFEB)

val primaryLightHighContrast = Color(0xFF350060)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF5F1B9B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2D1744)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF503967)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF49002F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF800D57)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FE)
val onBackgroundLightHighContrast = Color(0xFF1E1A22)
val surfaceLightHighContrast = Color(0xFFFFF7FE)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEBDEF0)
val onSurfaceVariantLightHighContrast = Color(0xFF28212E)
val outlineLightHighContrast = Color(0xFF48404E)
val outlineVariantLightHighContrast = Color(0xFF48404E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF332F37)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFF6E7FF)
//val surfaceDimLightHighContrast = Color(0xFFE0D7E2)
//val surfaceBrightLightHighContrast = Color(0xFFFFF7FE)
//val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightHighContrast = Color(0xFFFAF1FC)
//val surfaceContainerLightHighContrast = Color(0xFFF4EBF6)
//val surfaceContainerHighLightHighContrast = Color(0xFFEFE5F0)
//val surfaceContainerHighestLightHighContrast = Color(0xFFE9DFEB)

val primaryDark = Color(0xFFDDB8FF)
val onPrimaryDark = Color(0xFF490081)
val primaryContainerDark = Color(0xFF7334AF)
val onPrimaryContainerDark = Color(0xFFFFF8FD)
val secondaryDark = Color(0xFFD8BBF2)
val onSecondaryDark = Color(0xFF3C2653)
val secondaryContainerDark = Color(0xFF4D3664)
val onSecondaryContainerDark = Color(0xFFE7CAFF)
val tertiaryDark = Color(0xFFFFAFD4)
val onTertiaryDark = Color(0xFF620041)
val tertiaryContainerDark = Color(0xFF99266B)
val onTertiaryContainerDark = Color(0xFFFFF9F9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161219)
val onBackgroundDark = Color(0xFFE9DFEB)
val surfaceDark = Color(0xFF161219)
val onSurfaceDark = Color(0xFFE9DFEB)
val surfaceVariantDark = Color(0xFF4C4452)
val onSurfaceVariantDark = Color(0xFFCEC2D4)
val outlineDark = Color(0xFF978D9D)
val outlineVariantDark = Color(0xFF4C4452)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9DFEB)
val inverseOnSurfaceDark = Color(0xFF332F37)
val inversePrimaryDark = Color(0xFF7C3EB9)
//val surfaceDimDark = Color(0xFF161219)
//val surfaceBrightDark = Color(0xFF3C3740)
//val surfaceContainerLowestDark = Color(0xFF110D14)
//val surfaceContainerLowDark = Color(0xFF1E1A22)
//val surfaceContainerDark = Color(0xFF221E26)
//val surfaceContainerHighDark = Color(0xFF2D2830)
//val surfaceContainerHighestDark = Color(0xFF38333B)

val primaryDarkMediumContrast = Color(0xFFE0BDFF)
val onPrimaryDarkMediumContrast = Color(0xFF250045)
val primaryContainerDarkMediumContrast = Color(0xFFB273F1)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDDBFF7)
val onSecondaryDarkMediumContrast = Color(0xFF210A37)
val secondaryContainerDarkMediumContrast = Color(0xFFA186BA)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFB6D7)
val onTertiaryDarkMediumContrast = Color(0xFF330020)
val tertiaryContainerDarkMediumContrast = Color(0xFFE363A9)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF161219)
val onBackgroundDarkMediumContrast = Color(0xFFE9DFEB)
val surfaceDarkMediumContrast = Color(0xFF161219)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9FC)
val surfaceVariantDarkMediumContrast = Color(0xFF4C4452)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD3C7D8)
val outlineDarkMediumContrast = Color(0xFFAA9FB0)
val outlineVariantDarkMediumContrast = Color(0xFF89808F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE9DFEB)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2830)
val inversePrimaryDarkMediumContrast = Color(0xFF6423A1)
//val surfaceDimDarkMediumContrast = Color(0xFF161219)
//val surfaceBrightDarkMediumContrast = Color(0xFF3C3740)
//val surfaceContainerLowestDarkMediumContrast = Color(0xFF110D14)
//val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1A22)
//val surfaceContainerDarkMediumContrast = Color(0xFF221E26)
//val surfaceContainerHighDarkMediumContrast = Color(0xFF2D2830)
//val surfaceContainerHighestDarkMediumContrast = Color(0xFF38333B)

val primaryDarkHighContrast = Color(0xFFFFF9FC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFE0BDFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9FC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFDDBFF7)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9F9)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFB6D7)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF161219)
val onBackgroundDarkHighContrast = Color(0xFFE9DFEB)
val surfaceDarkHighContrast = Color(0xFF161219)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4C4452)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FC)
val outlineDarkHighContrast = Color(0xFFD3C7D8)
val outlineVariantDarkHighContrast = Color(0xFFD3C7D8)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE9DFEB)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF400072)
//val surfaceDimDarkHighContrast = Color(0xFF161219)
//val surfaceBrightDarkHighContrast = Color(0xFF3C3740)
//val surfaceContainerLowestDarkHighContrast = Color(0xFF110D14)
//val surfaceContainerLowDarkHighContrast = Color(0xFF1E1A22)
//val surfaceContainerDarkHighContrast = Color(0xFF221E26)
//val surfaceContainerHighDarkHighContrast = Color(0xFF2D2830)
//val surfaceContainerHighestDarkHighContrast = Color(0xFF38333B)


val Red500 = Color(0xFFE53935)
val Pink500 = Color(0xFFD81B60)
val Purple500 = Color(0xFF8E24AA)
val DeepPurple500 = Color(0xFF5E35B1)
val Indigo500 = Color(0xFF3949AB)
val Blue500 = Color(0xFF1E88E5)
val LightBlue500 = Color(0xFF039BE5)
val Cyan500 = Color(0xFF00ACC1)
val Teal500 = Color(0xFF00897B)
val Green500 = Color(0xFF43A047)
val LightGreen500 = Color(0xFF7CB342)
val Lime500 = Color(0xFFC0CA33)
val Yellow500 = Color(0xFFFDD835)
val Amber500 = Color(0xFFFFB300)
val Orange500 = Color(0xFFFF6F00)
val DeepOrange500 = Color(0xFFE64A19)
val Brown500 = Color(0xFF5D4037)
val Grey500 = Color(0xFF616161)
val BlueGrey500 = Color(0xFF455A64)


val allColors = listOf(
    Red500,
    Pink500,
    Purple500,
    DeepPurple500,
    Indigo500,
    Blue500,
    LightBlue500,
    Cyan500,
    Teal500,
    Green500,
    LightGreen500,
    Lime500,
    Yellow500,
    Amber500,
    Orange500,
    DeepOrange500,
)


